Proyecto1_CristhianBonilla/Views/Shared/Components/CartItemCount/CartItemCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto1_CristhianBonilla.Utils;
using Proyecto1_CristhianBonilla.ViewModels;

namespace Proyecto1_CristhianBonilla.Views.Shared.Components.CartItemCount
{
    public class CartItemCountViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var flights = HttpContext.Session.GetObjectFromJson<List<FlightOffer>>("CartStore");
            int itemCount = flights?.Count ?? 0;
            ViewData["CartItemCount"] = itemCount;
            return View(itemCount);
        }
    }
}

Proyecto1_CristhianBonilla/Views/Shared/_CartItemCount.cshtml
@{
    int itemCount = (int)ViewData["CartItemCount"];
}

<li class="nav-item">
    <a class="nav-link" href="@Url.Action("Cart", "Cart")">
        Carrito <span class="badge badge-pill badge-primary">@itemCount</span>
    </a>
</li>

Proyecto1_CristhianBonilla/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto1_CristhianBonilla</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proyecto1_CristhianBonilla.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Select2.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-black border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav ms-auto">
                        <!-- ms-auto para alinear a la derecha -->
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Historical" asp-action="Historical">Historico</a>
                        </li>
                        @await Component.InvokeAsync("CartItemCount")
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="EditUser" title="Editar usuario">
                                <i class="fas fa-user"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="LogOut" title="Cerrar sesión">
                                <i class="fas fa-sign-out-alt"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted bg-black">
        <footer class="border-top footer text-muted bg-black text-center">
            <div class="container">
                &copy; 2024 - Proyecto1_CristhianBonilla
                <br />
                <i class="fas fa-home"></i>
                &nbsp;&nbsp;&nbsp;
                <i class="fas fa-envelope"></i>
                &nbsp;&nbsp;&nbsp;
                <i class="fas fa-phone"></i>
            </div>
        </footer>
        <div class="container text-center">
            <i class="fas fa-home"></i>
            &nbsp;&nbsp;&nbsp;
            <i class="fas fa-envelope"></i>
            &nbsp;&nbsp;&nbsp;
            <i class="fas fa-phone"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/Select2.css" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/js/select2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>